# Generated by Django 4.0.4 on 2022-07-03 15:50

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_servicetypes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to=dashboard.models.bid_document_directory_path)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bid')),
            ],
        ),
    ]
